apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
      - name: {{ .Values.applicationName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.containerPort }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.readinessPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.livenessPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $value | default "" | quote }}
          {{- end }}