apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-svc
spec:
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - name: tcp
      protocol: TCP
      port: {{ .Values.service.exposePort }}
      targetPort: {{ .Values.service.containerPort }}